doc/baocaodoanweb/CodeWeb/Models/EF/DanhMuc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Web_61131562.Models.EF
{
    [Table("tb_DanhMuc")]
    public class DanhMuc : CommonAbstract
    {
        public DanhMuc()
        {
            this.TinTucs = new HashSet<TinTuc>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int MaDM { get; set; }
        [Required(ErrorMessage ="Tên danh mục không được để trống!")]
        [StringLength(150)]
        public string TenDM { get; set; }
        public string Alias { get; set; }
        //[StringLength(150)]
        //public string TypeCode { get; set; }
        public string LienKet { get; set; }
        public string MoTa { get; set; }
        [StringLength(150)]
        public string SeoTieuDe { get; set; }
        [StringLength(250)]
        public string SeoMoTa { get; set; }
        [StringLength(150)]
        public string SeoTuKhoa { get; set; }
        public bool IsActive { get; set; }
        public int ViTri { get; set; }
        public ICollection<TinTuc> TinTucs { get; set; }
        public ICollection<GioiThieu> GioiThieus { get; set; }
    }
}

doc/baocaodoanweb/CodeWeb/Areas/Admin/Controllers/DanhMucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_61131562.Models;
using Web_61131562.Models.EF;

namespace Web_61131562.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DanhMucController : Controller
    {
        private ApplicationDbContext _dbConnect = new ApplicationDbContext();
        // GET: Admin/DanhMuc
        public ActionResult Index()
        {
            var items = _dbConnect.DanhMucs;
            return View(items);
        }
        public ActionResult ThemMoi()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemMoi(DanhMuc model)
        {
            if (ModelState.IsValid)
            {
                model.NgayTao = DateTime.Now;
                model.NgaySua = DateTime.Now;
                model.Alias = Web_61131562.Models.Common.Filter.FilterChar(model.TenDM);
                _dbConnect.DanhMucs.Add(model);
                _dbConnect.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Sua(int id)
        {
            var item = _dbConnect.DanhMucs.Find(id);
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Sua(DanhMuc model)
        {
            if (ModelState.IsValid)
            {
                _dbConnect.DanhMucs.Attach(model);
                model.NgaySua = DateTime.Now;
                model.Alias = Web_61131562.Models.Common.Filter.FilterChar(model.TenDM);
                _dbConnect.Entry(model).Property(x => x.TenDM).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.MoTa).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.LienKet).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.Alias).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.SeoMoTa).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.SeoTuKhoa).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.SeoTieuDe).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.ViTri).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.NgaySua).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.NguoiSua).IsModified = true;
                _dbConnect.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Xoa(int id)
        {
            var item = _dbConnect.DanhMucs.Find(id);
            if(item != null)
            {
                //var XoaItem = _dbConnect.DanhMucs.Attach(item);
                _dbConnect.DanhMucs.Remove(item);
                _dbConnect.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

doc/baocaodoanweb/CodeWeb/Areas/Admin/Views/DanhMuc/Index.cshtml
@model IEnumerable<Web_61131562.Models.EF.DanhMuc>
@{
    ViewBag.Title = "Danh Mục";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/trangchu" class="nav-link">Trang Chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/danhmuc" class="nav-link">Danh Mục</a>
        </li>
    </ul>}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản Lý Danh Mục</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/admin/trangchu">Trang Chủ</a></li>
                    <li class="breadcrumb-item active">Danh Mục</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Danh Sách Danh Mục</h3>

            <div class="card-tools">
                <a href="/admin/danhmuc/themmoi" class="btn btn-primary">Thêm Mới</a>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Tên Danh Mục</th>
                        <th>Thứ Tự</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = 1;
                        foreach (var item in Model)
                        {
                            <tr id="trow_@item.MaDM">
                                <td>@i</td>
                                <td>@item.TenDM</td>
                                <td>@item.ViTri</td>
                                <td>
                                    <a href="/admin/danhmuc/sua/@item.MaDM" class="btn btn-sm btn-primary">Sửa</a>
                                    <a href="#" data-id="@item.MaDM" class="btn btn-sm btn-danger btnXoa">Xóa</a>
                                </td>
                            </tr>
                            i++;

                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">Không có bản ghi nào!</td>
                        </tr>

                    }
                </tbody>
            </table>
            
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@section scripts{
    <script>
        $(document).ready(function () {
            $('body').on('click', '.btnXoa', function () {
                var id = $(this).data("id");
                var conf = confirm('Bạn có muốn xóa bản ghi này không ?');
                if (conf == true) {
                    $.ajax({
                        url: '/admin/danhmuc/xoa',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    });
                }
            });
        });
    </script>
    } 

doc/baocaodoanweb/CodeWeb/Areas/Admin/Views/DanhMuc/Sua.cshtml
@model Web_61131562.Models.EF.DanhMuc
@{
    ViewBag.Title = "Cập Nhật Danh Mục";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang Chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/danhmuc" class="nav-link">Danh Mục</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Cập Nhật</a>
        </li>
    </ul>}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cập Nhật Danh Mục</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Danh Mục</a></li>
                    <li class="breadcrumb-item active">Cập Nhật</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông Tin Danh Mục</h3>
        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Sua", "DanhMuc", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(x=>x.MaDM)
                    <!-- your steps content here -->
                <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tên Danh Mục</label>
                        @Html.TextBoxFor(x => x.TenDM, new { @class = "form-control", @placeholder = "Tên Danh Mục" })
                        @Html.ValidationMessageFor(x => x.TenDM, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Alias</label>
                        @Html.TextBoxFor(x => x.Alias, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputLink">Liên Kết</label>
                        @Html.TextBoxFor(x => x.LienKet, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.LienKet, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Mô Tả</label>
                        @Html.TextAreaFor(x => x.MoTa, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Thứ Tự</label>
                        @Html.TextBoxFor(x => x.ViTri, new { @class = "form-control"})
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Tiêu Đề</label>
                        @Html.TextAreaFor(x => x.SeoTieuDe, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Mô Tả</label>
                        @Html.TextAreaFor(x => x.SeoMoTa, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Từ Khóa</label>
                        @Html.TextAreaFor(x => x.SeoTuKhoa, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <a href="/admin/danhmuc" class="btn btn-danger">Quay Lại</a>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>

                }

            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->

doc/baocaodoanweb/CodeWeb/Areas/Admin/Views/DanhMuc/ThemMoi.cshtml
@model Web_61131562.Models.EF.DanhMuc
@{
    ViewBag.Title = "Thêm Mới Danh Mục";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang Chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/danhmuc" class="nav-link">Danh Mục Mặt Hàng</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Thêm Mới</a>
        </li>
    </ul>}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thêm Mới Danh Mục</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Danh Mục</a></li>
                    <li class="breadcrumb-item active">Thêm Mới</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông Tin Thêm Mới Danh Mục</h3>
        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("ThemMoi", "DanhMuc", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <!-- your steps content here -->
                <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tên Danh Mục</label>
                        @Html.TextBoxFor(x => x.TenDM, new { @class = "form-control", @placeholder = "Tên Danh Mục" })
                        @Html.ValidationMessageFor(x => x.TenDM, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Alias</label>
                        @Html.TextBoxFor(x => x.Alias, new { @class = "form-control"})
                        @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputLink">Liên Kết</label>
                        @Html.TextBoxFor(x => x.LienKet, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.LienKet, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Mô Tả</label>
                        @Html.TextAreaFor(x => x.MoTa, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Thứ Tự</label>
                        @Html.TextBoxFor(x => x.ViTri, new { @class = "form-control", @Value = "1" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Tiêu Đề</label>
                        @Html.TextAreaFor(x => x.SeoTieuDe, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Mô Tả</label>
                        @Html.TextAreaFor(x => x.SeoMoTa, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Từ Khóa</label>
                        @Html.TextAreaFor(x => x.SeoTuKhoa, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <a href="/admin/danhmuc" class="btn btn-danger">Quay Lại</a>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
                    
                }

            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->