doc/baocaodoanweb/CodeWeb/Models/EF/TinTuc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web_61131562.Models.EF
{
    [Table("tb_TinTuc")]
    public class TinTuc : CommonAbstract
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int MaTT { get; set; }
        [Required(ErrorMessage ="Bạn không được để trống tiêu đề tin!")]
        [StringLength(150)]
        public string TieuDeTT { get; set; }
        public string TacGia { get; set; }
        public string Alias { get; set; }
        public string MoTa { get; set; }
        [AllowHtml]
        public string ChiTiet { get; set; }
        public string Anh { get; set; }
        public int MaDM { get; set; }
        public string SeoTieuDe { get; set; }
        public string SeoMoTa { get; set; }
        public string SeoTuKhoa { get; set; }
        public bool IsActive { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
    }
}

doc/baocaodoanweb/CodeWeb/Areas/Admin/Controllers/TinTucController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_61131562.Models;
using Web_61131562.Models.EF;

namespace Web_61131562.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, Nhân Viên")]
    public class TinTucController : Controller
    {
        private ApplicationDbContext _dbConnect = new ApplicationDbContext();
        // GET: Admin/TinTuc
        public ActionResult Index(string Searchtext,int? page)
        {
            var pageSize = 5;
            if(page == null)
            {
                page = 1;

            }
            IEnumerable<TinTuc> items = _dbConnect.TinTucs.OrderByDescending(x => x.MaTT);
            if (!string.IsNullOrEmpty(Searchtext))
            {
               items = items.Where(x => x.Alias.Contains(Searchtext) || x.TieuDeTT.Contains(Searchtext));
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
             items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }
        public ActionResult Them()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Them(TinTuc model)
        {
            if (ModelState.IsValid)
            {
                model.NgayTao = DateTime.Now;
                model.MaDM = 5;
                model.NgaySua = DateTime.Now;
                model.Alias = Web_61131562.Models.Common.Filter.FilterChar(model.TieuDeTT);
                _dbConnect.TinTucs.Add(model);
                _dbConnect.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Sua(int id)
        {
            var item = _dbConnect.TinTucs.Find(id);
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Sua(TinTuc model)
        {
            if (ModelState.IsValid)
            {
                model.NgaySua = DateTime.Now;
                model.Alias = Web_61131562.Models.Common.Filter.FilterChar(model.TieuDeTT);
                _dbConnect.TinTucs.Attach(model);
                _dbConnect.Entry(model).State = System.Data.Entity.EntityState.Modified;
                _dbConnect.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Xoa(int id)
        {
            var item = _dbConnect.TinTucs.Find(id);
            if(item != null)
            {
                _dbConnect.TinTucs.Remove(item);
                _dbConnect.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
        [HttpPost]
        public ActionResult IsActive(int id)
        {
            var item = _dbConnect.TinTucs.Find(id);
            if (item != null)
            {
                item.IsActive = !item.IsActive;
                _dbConnect.Entry(item).State = System.Data.Entity.EntityState.Modified;
                _dbConnect.SaveChanges();
                return Json(new { success = true, isActive = item.IsActive });
            }
            return Json(new { success = false });
        }
        [HttpPost]
        public ActionResult XoaTatCa(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',');
                if(items!=null && items.Any())
                {
                    foreach(var item in items)
                    {
                        var obj = _dbConnect.TinTucs.Find(Convert.ToInt32(item));
                        _dbConnect.TinTucs.Remove(obj);
                        _dbConnect.SaveChanges();
                    }
                }
                return Json(new { success = true });

            }
            return Json(new { success = false });
        }
    }

}

doc/baocaodoanweb/CodeWeb/Controllers/TinTucController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_61131562.Models;
using Web_61131562.Models.EF;

namespace Web_61131562.Controllers
{
    public class TinTucController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: TinTuc
        public ActionResult Index(int? page)
        {
            var pageSize = 5;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<TinTuc> items = db.TinTucs.OrderByDescending(x => x.NgayTao);
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }
        public ActionResult ChiTiet(int id)
        {
            var item = db.TinTucs.Find(id);
            return View(item);
        }
        public ActionResult Partial_TinTuc_TrangChu()
        {
            var items = db.TinTucs.Take(3).ToList();
            return PartialView(items);
        }
    }
}

doc/baocaodoanweb/CodeWeb/Areas/Admin/Views/TinTuc/Index.cshtml
@model PagedList.PagedList<Web_61131562.Models.EF.TinTuc>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Danh Sách Tin Tức";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/trangchu" class="nav-link">Trang Chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/danhmuc" class="nav-link">@ViewBag.Title</a>
        </li>
    </ul>}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản Lý Tin Tức</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/admin/trangchu">Trang Chủ</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">@ViewBag.Title</h3>

            <div class="card-tools">
                <a href="/admin/tintuc/them" class="btn btn-primary">Thêm Mới</a>
                <a href="#" class="btn btn-danger" id="BtnXoaTatCa">Xóa</a>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    @using (Html.BeginForm("index", "TinTuc", FormMethod.Get, new { }))
                    {

                        <div class="input-group input-group-sm">
                            @Html.TextBox("Searchtext", null, new { @class = "form-control" })
                            @*<input type="text" name="searchText" class="form-control">*@
                            <span class="input-group-append">
                                <button type="submit" class="btn btn-info btn-flat">Tìm Kiếm</button>
                            </span>
                        </div>
                    }

                </div>

            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th><input type="checkbox" id="ChonTatCa" /></th>
                        <th>STT</th>
                        <th>Hình Ảnh</th>
                        <th>Tiêu Đề Tin</th>
                        <th>Ngày Tạo</th>
                        @*//<th>Hiển Thị</th>*@
                        <th>Tác Giả</th>
                        <th style="width:150px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = ((ViewBag.Page - 1) * ViewBag.PageSize) + 1;
                        foreach (var item in Model)
                        {

                            var strCheck = item.IsActive ? "<i class = 'fa fa-check text-success'></i>" : "<i class='fas fa-times text-danger'></i>";
                        <tr id="trow_@item.MaTT">
                        <td><input type="checkbox" class="cbkItem" value="@item.MaTT" /></td>
                        <td class="text-center align-middle">@i</td>
                        <td class="text-center align-middle"><img src="@item.Anh" width="50" /></td>
                        <td>@item.TieuDeTT</td>
                        <td>@item.NgayTao.ToString("dd/MM/yyyy")</td>
                        <td>@item.TacGia</td>
                        <td class="text-center" style="white-space: nowrap; vertical-align: middle;">
                            <a href='#' data-id="@item.MaTT" class="btnActive">@Html.Raw(strCheck)</a>
                        </td>
                        <td>
                            <a href="/admin/tintuc/sua/@item.MaTT" class="btn btn-sm btn-primary">Sửa</a>
                            <a href="#" data-id="@item.MaTT" class="btn btn-sm btn-danger btnXoa">Xóa</a>
                        </td>
                    </tr>
                            i++;

                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">Không có bản ghi nào!</td>
                        </tr>

                    }
                </tbody>
            </table>
            <div class="row">
                <div class="col-6"></div>
                <div class="col-6" style="text-align:right;">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                </div>
            </div>

        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
@section styles {
    <style>
        th {
            white-space: nowrap !important;
        }
    </style>
}
<!-- /.content -->
@section scripts{
    <script>
        $(document).ready(function () {
            $('body').on('click', '#BtnXoaTatCa', function (e) {
                e.preventDefault();
                var str = "";
                var checkBox = $(this).parents('.card').find('tr td input:checkbox');
                var i = 0;
                checkBox.each(function () {
                    if (this.checked) {
                        checkBox.attr('selected', 'checked');
                        var _id = $(this).val();
                        if (i === 0) {
                            str += _id;
                        } else {
                            str += "," + _id;
                        }
                        i++;
                    } else {
                        checkBox.attr('selected', '');
                    }
                });
                if (str.length > 0) {
                    var conf = confirm('Bạn có muốn xóa bản ghi này không?');
                    if (conf === true) {
                        $.ajax({
                            url: '/admin/tintuc/xoaTatCa',
                            type: 'POST',
                            data: { ids: str },
                            success: function (rs) {
                                if (rs.success) {
                                    location.reload();
                                }
                            }
                        });
                    }
                }

            });


            $('body').on('change', '#ChonTatCa', function () {
                var checkStatus = this.checked;
                var checkBox = $(this).parents('.card-body').find('tr td input:checkbox');
                checkBox.each(function () {
                    this.checked = checkStatus;
                    if (this.checked) {
                        checkBox.attr('selected', 'checked');
                    } else {
                        checkBox.attr('selected', '');
                    }
                });
            });
            $('body').on('click', '.btnXoa', function () {
                var id = $(this).data("id");
                var conf = confirm('Bạn có muốn xóa bản ghi này không ?');
                if (conf == true) {
                    $.ajax({
                        url: '/admin/tintuc/xoa',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove();
                            }
                        }
                    });
                }
            });
            $('body').on('click', '.btnActive', function (e) {
                e.preventDefault();
                var btn = $(this);
                var id = btn.data("id");
                $.ajax({
                    url: '/admin/tintuc/IsActive',
                    type: 'POST',
                    data: { id: id },
                    success: function (rs) {
                        debugger;
                        if (rs.success) {
                            if (rs.isActive) {
                                btn.html("<i class='fa fa-check text-success'></i>");
                                //$(this).find("i").removeClass("fas fa-times text-danger");
                                //$(this).find("i").addClass("fa fa-check text-success");
                            } else {
                                btn.html("<i class='fas fa-times text-danger'></i>");
                            }
                        }

                    }
                });
            });
        });
    </script>
} 

doc/baocaodoanweb/CodeWeb/Areas/Admin/Views/TinTuc/Sua.cshtml
@model Web_61131562.Models.EF.TinTuc
@{
    ViewBag.Title = "Cập Nhật Tin Tức";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang Chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/tintuc" class="nav-link">Tin Tức</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Cập Nhật</a>
        </li>
    </ul>}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cập Nhật Tin Tức</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Tin Tức</a></li>
                    <li class="breadcrumb-item active">Cập Nhật</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông Tin Cập Nhật Tin Tức</h3>
        </div>
        <div class="card-body">
            @if (Model != null)
            {
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Sua", "TinTuc", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(x => x.MaTT)
                    @Html.HiddenFor(x => x.MaDM)
                    @Html.HiddenFor(x => x.NgayTao)
                    <!-- your steps content here -->
                <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tiêu Đề Tin</label>
                        @Html.TextBoxFor(x => x.TieuDeTT, new { @class = "form-control", @placeholder = "Tiêu Đề Tin" })
                        @Html.ValidationMessageFor(x => x.TieuDeTT, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Ảnh Đại Diện</label>
                        <div class="input-group">
                            <div class="custom-file">
                                @Html.TextBoxFor(x => x.Anh, new { @id = "txtAnh", @class = "form-control" })
                            </div>
                            <div class="input-group-append">
                                <input type="button" value="Tải Ảnh" onclick="BrowseServer('txtAnh');" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Mô Tả</label>
                        @Html.TextAreaFor(x => x.MoTa, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Chi Tiết</label>
                        @Html.TextAreaFor(x => x.ChiTiet, new { @class = "form-control", @id = "txtChiTiet" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Hiển Thị</label>
                        @Html.CheckBoxFor(x => x.IsActive)
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Tiêu Đề</label>
                        @Html.TextAreaFor(x => x.SeoTieuDe, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Mô Tả</label>
                        @Html.TextAreaFor(x => x.SeoMoTa, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Từ Khóa</label>
                        @Html.TextAreaFor(x => x.SeoTuKhoa, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Lưu</button>
                        <a href="/admin/tintuc" class="btn btn-danger">Quay Lại</a>
                    </div>
                </div>

                }

            </div>
            }

        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@section scripts{
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('txtChiTiet', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
            function BrowseServer(field) {
                var finder = new CKFinder();
                finder.selectActionFunction = function (fileUrl) {
                    document.getElementById(field).value = fileUrl;
                };
                finder.popup();
            }

    </script>
}

doc/baocaodoanweb/CodeWeb/Areas/Admin/Views/TinTuc/Them.cshtml
@model Web_61131562.Models.EF.TinTuc
@{
    ViewBag.Title = "Thêm Mới Tin Tức";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang Chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/tintuc" class="nav-link">Tin Tức</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Thêm Mới</a>
        </li>
    </ul>}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thêm Mới Tin Tức</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Tin Tức</a></li>
                    <li class="breadcrumb-item active">Thêm Mới</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông Tin Thêm Mới Tin Tức</h3>
        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Them", "TinTuc", FormMethod.Post, new { }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <!-- your steps content here -->
                <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tiêu Đề Tin</label>
                        @Html.TextBoxFor(x => x.TieuDeTT, new { @class = "form-control", @placeholder = "Tiêu Đề Tin" })
                        @Html.ValidationMessageFor(x => x.TieuDeTT, null, new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">Ảnh Đại Diện</label>
                        <div class="input-group">
                            <div class="custom-file">
                                @Html.TextBoxFor(x => x.Anh, new { @id = "txtAnh", @class = "form-control" })
                            </div>
                            <div class="input-group-append">
                                <input type="button" value="Tải Ảnh" onclick="BrowseServer('txtAnh');" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Mô Tả</label>
                        @Html.TextAreaFor(x => x.MoTa, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Chi Tiết</label>
                        @Html.TextAreaFor(x => x.ChiTiet, new { @class = "form-control", @id = "txtChiTiet" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Hiển Thị</label>
                        @Html.CheckBoxFor(x => x.IsActive, new {@checked = "@checked"})
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Tiêu Đề</label>
                        @Html.TextAreaFor(x => x.SeoTieuDe, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Mô Tả</label>
                        @Html.TextAreaFor(x => x.SeoMoTa, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">SEO Từ Khóa</label>
                        @Html.TextAreaFor(x => x.SeoTuKhoa, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Lưu</button>
                        <a href="/admin/tintuc" class="btn btn-danger">Quay Lại</a>
                    </div>
                </div>

                }

            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@section scripts{
    <script>
        $(document).ready(function () {
            CKEDITOR.replace('txtChiTiet', {
                customConfig: '/content/ckeditor/config.js',
                extraAllowedContent: 'span',
            });
        });
            function BrowseServer(field) {
                var finder = new CKFinder();
                finder.selectActionFunction = function (fileUrl) {
                    document.getElementById(field).value = fileUrl;
                };
                finder.popup();
            }
        
    </script>
    }